apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ruptura.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ruptura.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
