{{- if and (not .Values.auth.existingSecret) .Values.auth.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ruptura.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ruptura.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.auth.apiKey | quote }}
{{- end }}
