
"""EXPORTER service (port 8005) - Prometheus metrics + dashboard data aggregation."""
import logging
import sys
from datetime import datetime, timezone, timedelta

import uvicorn
from fastapi import FastAPI, Response
from prometheus_client import Counter, Gauge, generate_latest, CONTENT_TYPE_LATEST, CollectorRegistry, REGISTRY

sys.path.insert(0, "/app")
from shared import config, database
from shared.models import (
    AnomalySummary, DashboardData, DetectionResult, HealthResponse,
        TimeSeriesPoint,
        )

        logging.basicConfig(
            level=config.get_str("LOG_LEVEL"),
                format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
                )
                logger = logging.getLogger("exporter")

                app = FastAPI(title="MLOps Exporter", version="1.0.0")

                PREFIX = config.get_str("METRICS_PREFIX", "mlops_anomaly")

                # Nettoyer le registry pour éviter les duplications
                # (solution temporaire pour le déploiement)
                for collector in list(REGISTRY._collector_to_names.keys()):
                    if PREFIX in str(collector):
                            REGISTRY.unregister(collector)

                            # Prometheus metrics
                            _anomaly_total = Counter(f"{PREFIX}_total", "Total anomalies detected")
                            _anomaly_rate = Gauge(f"{PREFIX}_rate", "Anomaly rate (last 24h)")
                            _predictions_total = Counter(f"{PREFIX}_predictions_total", "Total predictions")
                            _cpu_gauge = Gauge(f"{PREFIX}_cpu_usage", "Latest CPU usage (normalized)")
                            _memory_gauge = Gauge(f"{PREFIX}_memory_usage", "Latest memory usage (normalized)")

                            # Track last-seen counts to drive Counter.inc() correctly
                            _last_anomaly_count = 0
                            _last_prediction_count = 0


                            def _get_summary(window_hours: int = 24) -> AnomalySummary:
                                since = (datetime.now(timezone.utc) - timedelta(hours=window_hours)).isoformat()
                                    with database.get_conn() as conn:
                                            total = conn.execute(
                                                        "SELECT COUNT(*) FROM raw_logs WHERE timestamp >= ?", (since,)
                                                                ).fetchone()[0]
                                                                        anomalies = conn.execute(
                                                                                    "SELECT COUNT(*) FROM raw_logs WHERE log_level='ERROR' AND timestamp >= ?", (since,)
                                                                                            ).fetchone()[0]
                                                                                                rate = anomalies / total if total > 0 else 0.0
                                                                                                    return AnomalySummary(
                                                                                                            total_anomalies_24h=anomalies,
                                                                                                                    anomaly_rate=rate,
                                                                                                                            total_predictions=total,
                                                                                                                                )


                                                                                                                                def _get_anomaly_series(window_hours: int = 24) -> list[TimeSeriesPoint]:
                                                                                                                                    since = (datetime.now(timezone.utc) - timedelta(hours=window_hours)).isoformat()
                                                                                                                                        with database.get_conn() as conn:
                                                                                                                                                rows = conn.execute(
                                                                                                                                                            """SELECT timestamp, 
                                                                                                                                                                                  CASE WHEN log_level='ERROR' THEN 1.0 ELSE 0.0 END as anomaly_score,
                                                                                                                                                                                                        (log_level='ERROR') as is_anomaly
                                                                                                                                                                                                                       FROM raw_logs WHERE timestamp >= ?
                                                                                                                                                                                                                                      ORDER BY timestamp LIMIT 500""",
                                                                                                                                                                                                                                                  (since,),
                                                                                                                                                                                                                                                          ).fetchall()
                                                                                                                                                                                                                                                              return [
                                                                                                                                                                                                                                                                      TimeSeriesPoint(
                                                                                                                                                                                                                                                                                  timestamp=r["timestamp"],
                                                                                                                                                                                                                                                                                              value=float(r["anomaly_score"]),
                                                                                                                                                                                                                                                                                                          is_anomaly=bool(r["is_anomaly"]),
                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                          for r in rows
                                                                                                                                                                                                                                                                                                                              ]


                                                                                                                                                                                                                                                                                                                              def _get_metric_series(window_hours: int = 24) -> list[TimeSeriesPoint]:
                                                                                                                                                                                                                                                                                                                                  since = (datetime.now(timezone.utc) - timedelta(hours=window_hours)).isoformat()
                                                                                                                                                                                                                                                                                                                                      with database.get_conn() as conn:
                                                                                                                                                                                                                                                                                                                                              rows = conn.execute(
                                                                                                                                                                                                                                                                                                                                                          """SELECT timestamp, value
                                                                                                                                                                                                                                                                                                                                                                         FROM raw_metrics WHERE timestamp >= ? AND metric_name='cpu_usage'
                                                                                                                                                                                                                                                                                                                                                                                        ORDER BY timestamp LIMIT 500""",
                                                                                                                                                                                                                                                                                                                                                                                                    (since,),
                                                                                                                                                                                                                                                                                                                                                                                                            ).fetchall()
                                                                                                                                                                                                                                                                                                                                                                                                                return [
                                                                                                                                                                                                                                                                                                                                                                                                                        TimeSeriesPoint(timestamp=r["timestamp"], value=float(r["value"] or 0.0))
                                                                                                                                                                                                                                                                                                                                                                                                                                for r in rows
                                                                                                                                                                                                                                                                                                                                                                                                                                    ]


                                                                                                                                                                                                                                                                                                                                                                                                                                    def _get_recent_anomalies(limit: int = 20) -> list[DetectionResult]:
                                                                                                                                                                                                                                                                                                                                                                                                                                        with database.get_conn() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                rows = conn.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            """SELECT id, timestamp, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CASE WHEN log_level='ERROR' THEN 1.0 ELSE 0.0 END as anomaly_score,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (log_level='ERROR') as is_anomaly,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              pod_name, namespace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             FROM raw_logs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHERE log_level='ERROR'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ORDER BY timestamp DESC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          LIMIT ?""",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (limit,),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ).fetchall()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          DetectionResult(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id=r["id"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  timestamp=r["timestamp"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              anomaly_score=float(r["anomaly_score"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          is_anomaly=bool(r["is_anomaly"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pod_name=r["pod_name"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  namespace=r["namespace"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for r in rows
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ]


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      def _update_prometheus_gauges() -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          """Update all Prometheus metrics from latest DB data."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              global _last_anomaly_count, _last_prediction_count

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  with database.get_conn() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          latest_metric = conn.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "SELECT value FROM raw_metrics WHERE metric_name='cpu_usage' ORDER BY timestamp DESC LIMIT 1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ).fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if latest_metric:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  _cpu_gauge.set(float(latest_metric["value"]))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          total = conn.execute("SELECT COUNT(*) FROM raw_logs").fetchone()[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  anomalies = conn.execute("SELECT COUNT(*) FROM raw_logs WHERE log_level='ERROR'").fetchone()[0]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # Increment counters by delta since last check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  delta_predictions = max(0, total - _last_prediction_count)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          delta_anomalies = max(0, anomalies - _last_anomaly_count)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if delta_predictions:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _predictions_total.inc(delta_predictions)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if delta_anomalies:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  _anomaly_total.inc(delta_anomalies)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          _last_prediction_count = total
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  _last_anomaly_count = anomalies

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 24h window anomaly rate for the gauge
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  row_24h = conn.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              """SELECT COUNT(*) as total, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    COUNT(CASE WHEN log_level='ERROR' THEN 1 END) as anomalies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   FROM raw_logs WHERE timestamp >= datetime('now', '-24 hours')"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ).fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if row_24h and row_24h[0]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               _anomaly_rate.set(row_24h[1] / row_24h[0])


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               @app.on_event("startup")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               async def startup() -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   database.init_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       logger.info("Exporter started")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       @app.get("/health", response_model=HealthResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       async def health() -> HealthResponse:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return HealthResponse(status="ok", service="exporter")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           @app.get("/metrics")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           async def metrics() -> Response:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               _update_prometheus_gauges()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   @app.get("/dashboard-data", response_model=DashboardData)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   async def dashboard_data(window: str = "1h") -> DashboardData:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if not window.endswith("h"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               window = "1h"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           hours = max(1, min(int(window[:-1]), 168))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               except ValueError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       hours = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           window = f"{hours}h"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return DashboardData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       anomaly_series=_get_anomaly_series(hours),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               metric_series=_get_metric_series(hours),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       summary=_get_summary(hours),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               recent_anomalies=_get_recent_anomalies(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       window=window,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           @app.get("/summary", response_model=AnomalySummary)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           async def summary() -> AnomalySummary:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return _get_summary()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   uvicorn.run("main:app", host="0.0.0.0", port=config.get_int("EXPORTER_PORT", 8005), reload=False)