apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: {{ .Values.namespace }}
  labels:
    app: collector
    app.kubernetes.io/name: mlops-anomaly-detection
spec:
  replicas: {{ .Values.services.collector.replicas }}
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccountName: mlops-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: collector
          image: {{ .Values.image.repository }}-collector:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
          ports:
            - containerPort: {{ .Values.services.collector.port }}
          envFrom:
            - configMapRef:
                name: mlops-config
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.services.collector.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.collector.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.collector.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
