apiVersion: v1
kind: Service
metadata:
  name: detector
  namespace: {{ .Values.namespace }}
  labels:
    app: detector
spec:
  selector:
    app: detector
  ports:
    - port: {{ .Values.services.detector.port }}
      targetPort: {{ .Values.services.detector.port }}
      protocol: TCP
      name: http
  type: ClusterIP
