apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: exporter
    app.kubernetes.io/name: mlops-anomaly-detection
spec:
  replicas: {{ .Values.services.exporter.replicas }}
  selector:
    matchLabels:
      app: exporter
  template:
    metadata:
      labels:
        app: exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.services.exporter.port }}"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      automountServiceAccountToken: false
      containers:
        - name: exporter
          image: {{ .Values.image.repository }}-exporter:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
          ports:
            - containerPort: {{ .Values.services.exporter.port }}
          envFrom:
            - configMapRef:
                name: mlops-config
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.services.exporter.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.exporter.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.exporter.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
