apiVersion: v1
kind: Service
metadata:
  name: {{ include "ruptura.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ruptura.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ruptura.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: 80
      targetPort: api
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ruptura.fullname" . }}-otlp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ruptura.labels" . | nindent 4 }}
  {{- with .Values.otlpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otlpService.type }}
  selector:
    {{- include "ruptura.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-http
      port: 4317
      targetPort: otlp
      protocol: TCP
      {{- if and (eq .Values.otlpService.type "NodePort") .Values.otlpNodePort }}
      nodePort: {{ .Values.otlpNodePort }}
      {{- end }}
