apiVersion: v1
kind: Service
metadata:
  name: trainer
  namespace: {{ .Values.namespace }}
  labels:
    app: trainer
spec:
  selector:
    app: trainer
  ports:
    - port: {{ .Values.services.trainer.port }}
      targetPort: {{ .Values.services.trainer.port }}
      protocol: TCP
      name: http
  type: ClusterIP
