<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { fetchAlerts } from '../lib/api'
  import type { Alert } from '../lib/api'

  let alerts: Alert[] = []
  let loading = true
  let error = ''
  let filter = 'active'
  let interval: ReturnType<typeof setInterval>

  async function load() {
    try {
      alerts = await fetchAlerts()
      error = ''
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
    } finally {
      loading = false
    }
  }

  onMount(() => {
    load()
    interval = setInterval(load, 15_000)
  })
  onDestroy(() => clearInterval(interval))

  function matchFilter(a: Alert): boolean {
    if (filter === 'active')   return !a.resolved_at
    if (filter === 'resolved') return !!a.resolved_at
    return true
  }
  $: filtered = alerts.filter(matchFilter)

  $: activeCount   = alerts.filter(a => !a.resolved_at).length
  $: resolvedCount = alerts.filter(a => !!a.resolved_at).length

  function severityColor(s: string): string {
    switch (s) {
      case 'critical': return 'var(--red)'
      case 'warning':  return 'var(--yellow)'
      case 'info':     return 'var(--cyan)'
      default:         return 'var(--muted)'
    }
  }

  function fmtTime(ts: string): string {
    if (!ts) return '—'
    return new Date(ts).toLocaleString()
  }

  function relTime(ts: string): string {
    if (!ts) return ''
    const delta = Date.now() - new Date(ts).getTime()
    if (delta < 60_000)     return `${Math.round(delta / 1000)}s ago`
    if (delta < 3_600_000)  return `${Math.round(delta / 60_000)}m ago`
    return `${Math.round(delta / 3_600_000)}h ago`
  }
</script>

<div class="alerts-page">
  <div class="page-header">
    <div>
      <h1 class="page-title">Alerts</h1>
      <p class="page-sub">Live anomaly alerts generated by the rupture detection engine.</p>
    </div>
    <button class="refresh-btn" on:click={load} title="Refresh">↻</button>
  </div>

  <!-- summary bar -->
  <div class="summary">
    <div class="stat crit"><span class="slabel">Active</span><span class="sval">{activeCount}</span></div>
    <div class="stat ok"><span class="slabel">Resolved</span><span class="sval">{resolvedCount}</span></div>
    <div class="stat"><span class="slabel">Total</span><span class="sval">{alerts.length}</span></div>

    <div class="filters">
      {#each [['all','All'],['active','Active'],['resolved','Resolved']] as [f, label]}
        <button class="filter-btn" class:active={filter === f} on:click={() => { filter = f }}>
          {label}
        </button>
      {/each}
    </div>
  </div>

  {#if loading}
    <div class="state">Loading alerts…</div>
  {:else if error}
    <div class="state err">{error}</div>
  {:else if filtered.length === 0}
    <div class="state">
      {#if filter === 'active'}
        <div class="empty-icon">◉</div>
        <strong>No active alerts</strong>
        <p>The engine has not detected any anomalies matching the current filter.</p>
      {:else}
        No alerts to display.
      {/if}
    </div>
  {:else}
    <div class="alert-list">
      {#each filtered as a (a.id)}
        <div class="alert-card" class:resolved={!!a.resolved_at}>
          <div class="alert-top">
            <span class="sev-badge" style="color:{severityColor(a.severity)};border-color:{severityColor(a.severity)}20;background:{severityColor(a.severity)}10">
              {a.severity.toUpperCase()}
            </span>
            <span class="alert-host">{a.host}</span>
            <span class="alert-metric">{a.metric}</span>
            <span class="alert-val">val={a.value.toFixed(3)}</span>
            <span class="alert-ts">{relTime(a.created_at)}</span>
            {#if a.resolved_at}
              <span class="resolved-badge">resolved</span>
            {:else}
              <span class="active-badge">active</span>
            {/if}
          </div>
          <div class="alert-msg">{a.message}</div>
          <div class="alert-meta">
            <span class="slabel">Created</span> {fmtTime(a.created_at)}
            {#if a.resolved_at}
              &nbsp;·&nbsp; <span class="slabel">Resolved</span> {fmtTime(a.resolved_at)}
            {/if}
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .alerts-page { display: flex; flex-direction: column; gap: 16px; }

  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .page-title { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
  .page-sub { font-size: 13px; color: var(--muted); }

  .refresh-btn {
    background: none;
    border: 1px solid var(--border);
    color: var(--muted);
    padding: 6px 12px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    transition: color 0.15s;
  }
  .refresh-btn:hover { color: var(--purple); }

  .summary {
    display: flex;
    align-items: center;
    gap: 20px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 12px 18px;
    flex-wrap: wrap;
  }

  .stat { display: flex; flex-direction: column; gap: 1px; }
  .slabel { font-size: 9px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.07em; }
  .sval { font-size: 20px; font-weight: 700; font-variant-numeric: tabular-nums; line-height: 1; }
  .stat.ok .sval  { color: var(--green); }
  .stat.crit .sval { color: var(--red); }

  .filters {
    display: flex;
    gap: 4px;
    margin-left: auto;
  }

  .filter-btn {
    background: var(--surface2);
    border: 1px solid var(--border);
    color: var(--muted);
    padding: 5px 12px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 12px;
    font-weight: 500;
    transition: color 0.15s, border-color 0.15s, background 0.15s;
  }
  .filter-btn:hover { color: var(--text); }
  .filter-btn.active { color: var(--purple); border-color: var(--purple); background: rgba(168,85,247,0.08); }

  .state {
    text-align: center;
    color: var(--muted);
    padding: 48px 24px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    line-height: 1.6;
  }
  .state.err { color: var(--red); border-color: rgba(239,68,68,0.3); }

  .empty-icon { font-size: 28px; color: var(--border); margin-bottom: 4px; }

  .alert-list { display: flex; flex-direction: column; gap: 8px; }

  .alert-card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 12px 16px;
    display: flex;
    flex-direction: column;
    gap: 6px;
    transition: border-color 0.15s;
  }
  .alert-card:not(.resolved) { border-left: 3px solid var(--red); }
  .alert-card.resolved { opacity: 0.6; }

  .alert-top {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
  }

  .sev-badge {
    font-size: 9px;
    font-weight: 800;
    padding: 2px 7px;
    border-radius: 4px;
    border: 1px solid;
    font-family: 'JetBrains Mono', monospace;
    letter-spacing: 0.06em;
    flex-shrink: 0;
  }

  .alert-host {
    font-weight: 600;
    font-size: 13px;
    font-family: 'JetBrains Mono', monospace;
  }

  .alert-metric {
    font-size: 11px;
    color: var(--muted);
    font-family: 'JetBrains Mono', monospace;
  }

  .alert-val {
    font-size: 11px;
    color: var(--yellow);
    font-family: 'JetBrains Mono', monospace;
    margin-left: auto;
  }

  .alert-ts { font-size: 10px; color: var(--muted); }

  .active-badge {
    font-size: 9px;
    font-weight: 700;
    color: var(--red);
    background: rgba(239,68,68,0.1);
    border: 1px solid rgba(239,68,68,0.3);
    padding: 1px 7px;
    border-radius: 20px;
    animation: alert-pulse 2s ease-in-out infinite;
  }
  @keyframes alert-pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.6; } }

  .resolved-badge {
    font-size: 9px;
    font-weight: 700;
    color: var(--green);
    background: rgba(0,229,160,0.08);
    border: 1px solid rgba(0,229,160,0.2);
    padding: 1px 7px;
    border-radius: 20px;
  }

  .alert-msg {
    font-size: 13px;
    color: var(--text);
    line-height: 1.5;
  }

  .alert-meta {
    font-size: 10px;
    color: var(--muted);
    font-family: 'JetBrains Mono', monospace;
  }
</style>
