#!/usr/bin/env bash
# Regenerates install/ruptura.yaml from the Helm chart — the one-command
# install path documented in the README. Helm remains the advanced/production
# path (helm install ...); this script exists so the two never drift.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
namespace="ruptura-system"
out="$repo_root/install/ruptura.yaml"

# helm/Chart.yaml's appVersion is a chart-packaging concern (bumped at chart
# release time) and has been observed to drift behind the actual binary
# version — see docs/history for the version-const drift this project has
# hit before. Pin the image tag explicitly from the real source of truth
# (the version const in main.go, which CI tags published images with) so a
# fresh `kubectl apply` never pulls a stale or nonexistent tag.
version_const="$(grep -oP '(?<=^const version = ")[^"]+' "$repo_root/workdir/cmd/ruptura/main.go")"
if [[ -z "$version_const" ]]; then
  echo "error: could not read version const from workdir/cmd/ruptura/main.go" >&2
  exit 1
fi
image_tag="v${version_const}"

{
  echo "# Generated by scripts/render-install-manifest.sh — do not edit directly."
  echo "# Regenerate with: ./scripts/render-install-manifest.sh"
  echo "#"
  echo "# One-command install:"
  echo "#   kubectl apply -f https://raw.githubusercontent.com/benfradjselim/ruptura/main/install/ruptura.yaml"
  echo "#   kubectl -n $namespace get pods"
  echo "#   kubectl -n $namespace logs job/ruptura-init-apikey   # prints the generated API key"
  echo "#"
  echo "apiVersion: v1"
  echo "kind: Namespace"
  echo "metadata:"
  echo "  name: $namespace"
  echo "---"
  helm template ruptura "$repo_root/helm" \
    --namespace "$namespace" \
    --set ui.enabled=true \
    --set autoGenerateApiKey=true \
    --set image.tag="$image_tag" \
    --set ui.image.tag="$image_tag"
} > "$out"

echo "Wrote $out (image tag: $image_tag)"
