apiVersion: v2
name: ruptura
description: Predictive failure detection engine for cloud-native infrastructure
type: application
version: 0.2.0
appVersion: "6.2.2"
home: https://benfradjselim.github.io/ruptura/
sources:
  - https://github.com/benfradjselim/ruptura
keywords:
  - observability
  - kubernetes
  - predictive
  - sre
  - cncf
maintainers:
  - name: Selim Benfradj
    email: benfradjselim@gmail.com
